### ISSUE TITLE
Netcore2 on mac Error

### ISSUE THREAD

**Issue by navidehsa** [mheyman/Isopoh.Cryptography.Argon2#11]
I am using this on Netcore2 and get this error when trying to run the application throw mac os.
The type initializer for Isopoh.Cryptography.secureArray.SecureArray throw new exception.

**Comment by mheyman** [comment]
I believe I have fixed the issue. I have never been completely certain when the CLR evaluates static functions and apparently it changed in .net core at some point. I don't have easy access to a mac to test on so the current code hasn't been tested on a mac. Good luck! :-)

**Comment by ffMathy** [comment]
I am experiencing the same issue.

**Comment by ffMathy** [comment]
But on Linux instead.

**Comment by ffMathy** [comment]
Actually, I wasn't on the latest version. The problem is indeed fixed, and the issue can be closed!
