### ISSUE TITLE
Strip Base64 padding 

### ISSUE THREAD

**Issue by DarkCoderX** [mheyman/Isopoh.Cryptography.Argon2#18]
The `Argon2.Hash(password);` method creates a hash string that contains B64 padding in salt and password hash. The hash formatting [spec](https://github.com/P-H-C/phc-string-format/blob/master/phc-sf-spec.md#b64) does not allow this.

The padding cause interoperability problems with stricter implementations like [node-argon2](https://github.com/ranisalt/node-argon2)

**Comment by mheyman** [comment]
Thanks for pointing this out - I was unaware that the base64 encoding was non-standard.

**Comment by mheyman** [comment]
It turns out, at one point I was aware of it because there are comments in the base64 decoding code about it. Well, now it is fixed and I've pushed a new version to nuget.org.
