### ISSUE TITLE
Any chance you would get this to work with csproj files?

### ISSUE THREAD

**Issue by RikWaspcroft** [mheyman/Isopoh.Cryptography.Argon2#2]

**Comment by mheyman** [comment]
I don't plan to port it to .csproj files until Visual Studio moves back to .csproj from the .xproj/project.json combination - which I believe will happen at the next update of Visual Studio.

**Comment by mheyman** [comment]
I just upgraded to Visual Studio 2017 which converted the .xproj files to .csproj. Unfortunately, I suspect your question was for earlier versions of Visual Studio that don't support the newer .csproj files.
