### ISSUE TITLE
Cannot install Nuget package in project with 4.6.1 Framework

### ISSUE THREAD

**Issue by marcells** [mheyman/Isopoh.Cryptography.Argon2#3]
I get an error, when I try to install the Nuget package to a project which targets .NET Framework 4.6.1.

`Could not install package 'Isopoh.Cryptography.Argon2 1.0.0'. You are trying to install this package into a project that targets '.NETFramework,Version=v4.6.1', but the package does not contain any assembly references or content files that are compatible with that framework. For more information, contact the package author.`

**Comment by mheyman** [comment]
I cannot repeat but I recently pushed a new version that targets .NETStandard 1.3 instead of 1.6 - if you try with that, maybe it will work for you.

**Comment by marcells** [comment]
Now it is working. Thank you!
