### ISSUE TITLE
error CS0103: The name 'Argon2' does not exist in the current context

### ISSUE THREAD

**Issue by jmpt16** [mheyman/Isopoh.Cryptography.Argon2#53]
I installed the package, [per the instructions](https://github.com/mheyman/Isopoh.Cryptography.Argon2?tab=readme-ov-file#installation), yet I still get the above mentioned error [with the test code provided](https://github.com/mheyman/Isopoh.Cryptography.Argon2?tab=readme-ov-file#usage). What am I doing wrong?

For reference I'm using VS Code with .NET 7.

**Comment by mheyman** [comment]
Finally got around to clarifying the example code. The examples now have `using`s and a more modern C# style.
