### ISSUE TITLE
Documentation Typos

### ISSUE THREAD

**Issue by CarbonFactory** [mheyman/Isopoh.Cryptography.Argon2#7]
_**To**_ is missing in 2nd line below in the `argon2Verify` variable:

` var argon2ToVerify = new Argon2(configOfPasswordToVerify);`
` using(var hashToVerify = argon2Verify.Hash())`

_**A**_ is missing in the 3rd line below in the `argon2` variable:

`var argon2A = new Argon2(config);`
`string hashString;`
`using(SecureArray<byte> hashA = argon2.Hash())`

**Comment by mheyman** [comment]
Thanks, fixed.
