### ISSUE TITLE
Memory leak

### ISSUE THREAD

**Issue by Wintereise** [mheyman/Isopoh.Cryptography.Argon2#8]
Sample code:

```
using System;
using Isopoh.Cryptography.Argon2;

namespace SnippetTester
{
    class Program
    {
        static void Main(string[] args)
        {
            for (int i = 0; i <= 1000000; i++)
            {
                Console.WriteLine("Argon2 (b,b) is: " + Argon2.Verify("$argon2i$v=19$m=65536,t=3,p=1$M2f6+jnVc4dyL3BfMQRzoA==$jO/fOrgqxX90XDVhiYZgIVJJcw0lzIXtRFRCEggXYV8=", "b"));
            }
        }
    }
}
```

Expected: things work ok, without ballooning to take up all system memory.

Actually: 

![image](https://user-images.githubusercontent.com/5137170/31534622-b273d04c-b032-11e7-92c4-d983df480adf.png)

What's in the heap (around 5GB allocated at this stage:)

![image](https://user-images.githubusercontent.com/5137170/31534682-ea6ac91a-b032-11e7-89ac-2c204fe67930.png)

**Comment by mheyman** [comment]
Good catch! It took me a while to track it down. There was also an associated (but not directly associated) lock leak which I consider a little bit worse. Fixed with a unit test in version 1.0.5.
